### ISSUE TITLE
Unable to localize results descriptions

### ISSUE THREAD

**Issue by toniopelo** [stadiamaps/maplibre-search-box#3]
We should have a way of localizing "Locality in France" or "Venue in France" label under each result title IMO.
See screenshot for an example.

![image](https://github.com/stadiamaps/maplibre-search-box/assets/9287511/48b24db7-f49b-4653-86ce-860c25b4fcff)

**Comment by ianthetechie** [comment]
Thanks for bringing this up @toniopelo (and sorry for not noticing this and your other PR; something is up with my GitHub email notifications)!

I'm also quite interested to improve the localization. Let's try to specify the desired outcomes a bit better.

First, under what conditions does the subtext change? My suggestion would be that this is dependent on the user's browser (`Accept-Language` headers, specifically). So if, say, my device is set to prefer French, it would show some text in French.

Second, we are not entirely satisfied with the "Venue in France" style of representing things to be completely honest. These terms are rather specific to the API schema, which is itself based on [Who's on First placetypes](https://github.com/whosonfirst/whosonfirst-placetypes#here-is-a-pretty-picture), but these terms don't actually mean anything to the average user. We have considered replacing these "place type" qualifiers with a simplified set of icons. 

So, one way we could simplify things (and avoid having to localize a technical string that isn't going to be that useful to most end users anyways) is to have the subtext line just be like "<icon> France" (or, for an example where the English name is different, "<icon> Deutschland"). This would definitely result in showing less information, but I think there is probably a balance to be found. Do you have any thoughts on this?
